### ISSUE TITLE
unable to commit

### ISSUE THREAD

**Issue by lenigr01** [Aequivinius/uibk-python#290]
Hello! I just wanted to finish my exercise 5. But my repl does not commit. Every time I try, the page reloads and it does not push. Moreover, I can not see my commit in my repository. What can I do? Thank you in anticipation!

**Comment by Aequivinius** [comment]
Check if you've linked your replit and your github account in your replit account settings as seen on the image below: 

<img width="654" alt="Capture d’écran 2021-04-19 à 10 30 47" src="https://user-images.githubusercontent.com/11438440/115205949-5dbf0500-a0fa-11eb-9956-c9e66247ae6f.png">

Otherwise, you can download your changes and upload them manually to github. Let me know if this works and have a good start into your week!

**Comment by lenigr01** [comment]
Thank you! I checked my replit account settings and everything is fine. Yesterday evening, I downloaded my changes and I uploaded them manually to github. It worked!
