### ISSUE TITLE
Übung 10 

### ISSUE THREAD

**Issue by juls97** [Aequivinius/uibk-python#425]
Hallo allerseits, 

ich hab ein Problem beim öffnen/importieren des Corpus für die Übung:

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/80048102/120069635-4541f300-c087-11eb-8877-26c0da6f91b0.png">

Kann mir leider die Fehlermeldung: FileNotFoundError: [Errno 2] No such file or directory: '../exercise-5/corpus/' 
nicht erklären, habs auch mit dem neuen Corpus von Übung 10 probiert, kommt aber die gleiche Meldung. Weiß zufällig jemand an was das liegt?

Lg Julia

**Comment by Aequivinius** [comment]
It's difficult to say because I can't see the most recent version of your repository, but you probably created your notebook file in the root directory (`uibk-python`), rather than in the `uibk-python/exercise-10` directory: When you launch `jupyter`, navigate to the `exercise-10` directory, and create your notebook there. 

<img width="365" alt="Capture d’écran 2021-05-31 à 10 42 35" src="https://user-images.githubusercontent.com/11438440/120167015-8825d700-c1fd-11eb-8b70-de28df920310.png">

<img width="1146" alt="Capture d’écran 2021-05-31 à 10 42 55" src="https://user-images.githubusercontent.com/11438440/120167032-8c51f480-c1fd-11eb-8c06-fc7473dcf76f.png">

From this directory, you have to go up one directory (`..`) to get to the root and then to the `exercise-5` directory, so the relative path is `../exercise-5/corpus`. For the new corpus however, you are already in the right directory, so the path is just `corpus`. (Alternatively, for greater clarity, you could specify the path to the new corpus as `../exercise-10/corpus`, which would mean you go one directory up from `exercise-10`, then go back into `exercise-10`.)
